/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_carlosmoncada;

import java.awt.Rectangle;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Em
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        nombreartistico.setVisible(false);
        txt_nombreartistico.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_contraseñas = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        nombreartistico = new javax.swing.JLabel();
        txt_nombreartistico = new javax.swing.JTextField();
        checksillo = new javax.swing.JCheckBox();
        txt_username = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel4.setText("Username");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Edad");

        nombreartistico.setText("Nombre Artistico");

        checksillo.setText("Artista");
        checksillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checksilloActionPerformed(evt);
            }
        });

        jButton3.setText("Crear usuario");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                                    .addComponent(nombreartistico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_nombreartistico, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sp_edad)
                                        .addComponent(txt_contraseñas)
                                        .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(checksillo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton3)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checksillo)
                .addGap(86, 86, 86)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_contraseñas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreartistico)
                            .addComponent(txt_nombreartistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jButton3)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel3.setText("Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setText("Iniciar sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Usuario");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_usuario)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checksilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checksilloActionPerformed
        if (checksillo.isSelected()) {
            nombreartistico.setVisible(true);
            txt_nombreartistico.setVisible(true);
        } else {
            nombreartistico.setVisible(false);
            txt_nombreartistico.setVisible(false);

        }

    }//GEN-LAST:event_checksilloActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jDialog1.pack();
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (checksillo.isSelected()) {
            String username = txt_username.getText();
            String contraseña = txt_contraseñas.getText();
            int edad = (int) sp_edad.getValue();
            String nombreartistico = txt_nombreartistico.getText();
            int crear = 0;
            ArrayList<Usuarios> usuarios = new ArrayList();

            try {

                File archivo = new File("./usuarios.lab");
                if (archivo.exists()) {
                    FileInputStream fw = new FileInputStream(archivo);
                    ObjectInputStream bw = new ObjectInputStream(fw);

                    try {
                        Usuarios temp = new Usuarios();
                        while ((temp = (Usuarios) bw.readObject()) != null) {
                            usuarios.add(temp);
                        }
                        for (int i = 0; i < usuarios.size(); i++) {
                            if (username.equalsIgnoreCase(usuarios.get(i).getUsername())) {
                                crear++;
                            }
                        }
                    } catch (Exception e) {

                    }
                    fw.close();
                    bw.close();
                }
                if (crear == 0) {
                    if (edad > 12) {
                        usuarios.add(new Artistas(nombreartistico, username, contraseña, edad));

                        FileOutputStream fws = new FileOutputStream(archivo);
                        ObjectOutputStream bws = new ObjectOutputStream(fws);
                        for (int i = 0; i < usuarios.size(); i++) {
                            bws.writeObject((Usuarios) usuarios.get(i));
                        }
                        bws.flush();
                        bws.close();
                        fws.close();
                        JOptionPane.showMessageDialog(null, "Usuario creado");
                        jDialog1.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Edad incorrecta");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Usuario repetido");

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            String username = txt_username.getText();
            String contraseña = txt_contraseñas.getText();
            int edad = (int) sp_edad.getValue();

            int crear = 0;
            ArrayList<Usuarios> usuariosx = new ArrayList();
            try {
                File archivo = new File("./usuarios.lab");

                if (archivo.exists()) {
                    FileInputStream fw = new FileInputStream(archivo);
                    ObjectInputStream bw = new ObjectInputStream(fw);

                    try {
                        Usuarios temp = new Usuarios();
                        while ((temp = (Usuarios) bw.readObject()) != null) {
                            usuariosx.add(temp);
                        }
                        for (int i = 0; i < usuariosx.size(); i++) {
                            if (username.equalsIgnoreCase(usuariosx.get(i).getUsername())) {
                                crear++;
                            }
                        }
                    } catch (Exception e) {

                    }
                    fw.close();
                    bw.close();
                }
                if (crear == 0) {
                    if (edad >= 12) {
                        usuariosx.add(new Cliente(username, contraseña, edad));

                        FileOutputStream fws = new FileOutputStream(archivo);
                        ObjectOutputStream bws = new ObjectOutputStream(fws);
                        for (int i = 0; i < usuariosx.size(); i++) {
                            bws.writeObject(usuariosx.get(i));
                        }
                        bws.flush();
                        bws.close();
                        fws.close();
                        JOptionPane.showMessageDialog(null, "Usuario creado");
                        jDialog1.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Edad incorrecta");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Usuario repetido");

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        txt_contraseñas.setText("");
        txt_username.setText("");
        txt_nombreartistico.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String usuario = txt_usuario.getText();
        String contraseña = txt_contraseña.getText();
        try {

            FileInputStream fw = new FileInputStream("./usuarios.lab");
            ObjectInputStream bw = new ObjectInputStream(fw);
            ArrayList<Usuarios> usuarios = new ArrayList();
            try {

                Usuarios temp = new Usuarios();
                while ((temp = (Usuarios) bw.readObject()) != null) {
                    usuarios.add(temp);
                }
            } catch (Exception e) {
            }
            int contusername = 0;
            int contcontraseña = 0;
            int indice = 0;
            for (int i = 0; i < usuarios.size(); i++) {
                if (usuario.equalsIgnoreCase(usuarios.get(i).getUsername())) {
                    contusername++;
                    indice = i;
                }
                if (contraseña.equalsIgnoreCase(usuarios.get(i).getContraseña())) {
                    contcontraseña++;
                }
            }

            if (contusername > 0 && contcontraseña > 0) {
                if (usuarios.get(indice) instanceof Cliente) {
                    Pantalla p = new Pantalla();
                    p.setLocationRelativeTo(null);
                    p.setBounds(new Rectangle(1000, 900));
                    p.setVisible(true);
                } else {
                    Artistass s = new Artistass();
                    s.setLocationRelativeTo(null);
                    s.setBounds(new Rectangle(1000, 900));
                    s.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuario incorrecto");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checksillo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nombreartistico;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_contraseñas;
    private javax.swing.JTextField txt_nombreartistico;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

}
